name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up CMake
      run: sudo apt-get install -y cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
